README.md
qc_baselib/__init__.py
qc_baselib/configuration.py
qc_baselib/models/__init__.py
qc_baselib/models/common.py
qc_baselib/models/config.py
qc_baselib/models/report.py
qc_baselib/report.py
tests/test_report.py

This PR adds a enumerator for the issue severity as a model for user help.
1. [Add IssueSeverity enum](https://github.com/asam-ev/qc-baselib-py/commit/496d7030b21631567e78d81205d7f86efa7340b6)
2. [Add test using new enum](https://github.com/asam-ev/qc-baselib-py/commit/0e3b3ec0ef0bdfe5b58806a3d3e9d3ac7ce242a5)
1. Unit-test passing with the addition of the enum.
**Notes**
- None.

Add issue severity enum

---

README.md
qc_baselib/__init__.py
qc_baselib/models/__init__.py
qc_baselib/models/result.py
qc_baselib/result.py
tests/data/demo_checker_bundle.xqar
tests/data/demo_checker_bundle_extended.xqar
tests/data/result_test_output.xqar
tests/test_result.py

This PR addresses the Result Schema updates in order to have the Python base library in sync with the latest schema.
1. Add metadata to the schema
2. Add checker status to the schema
3. Add rules definition to the schema
4. Add addressed rules to checkers
5. Add rule uid to issues
6. Update Result public interface to take into account new schema
7. Updated unit-test to include new schema
1. Unit-test are passing with the updates and additions.
**Notes**
- None

Support the new result file schema

---

qc_baselib/models/result.py
qc_baselib/result.py
tests/data/demo_checker_bundle_extended.xqar
tests/data/result_test_output.xqar
tests/test_result.py

This PR adds the `DomainSpecificInfo` to the `IssueType`.
It also fixes some missing details from the previous schema update in the lib.
1. Add `DomainSpecificInfo` to the `IssueType`
2. Add missing location elements methods for Results
3. Extend tests to check all added and updated cases
1. Unit-test are passing as intended after updates.
**Notes**
- None.

Add domain specific info to result

---

qc_baselib/models/common.py
qc_baselib/models/config.py
qc_baselib/models/result.py

This PR adds a refactor in the tag declaration in the Type usage instead of in the Type definition. This allows us to use the same type in different places with different element tags.
1. [Update tag element at type usage not at type on common models](https://github.com/asam-ev/qc-baselib-py/commit/f6f61e016eeb439c16522014be4e913c04dbc047) 
2. [Update tag element at type usage not at type on result models](https://github.com/asam-ev/qc-baselib-py/commit/8ae654bf21a63f302ba451c008269bfc2014ec32) 
3. [Update tag element at type usage not at type on config models](https://github.com/asam-ev/qc-baselib-py/commit/0b07a6d7663259afe6a493aeff4c57047ae4b3ab)
1. Unit-test are working with the new refactor.
**Notes**
- None

Refactor tag on type usage instead of type definition

---

qc_baselib/result.py
tests/test_result.py

This PR fixes a typo on the `get_issues_by_rule_uid` which was `get_issues_by_rule_id` previously.
1. Fix typo on get issues by rule uid method
2. Fix tests using the new method
1. Unit-test are passing with the changes.
**Notes**
- None

Fix typo on get issues method

---

README.md
qc_baselib/models/result.py
qc_baselib/result.py
tests/data/result_test_output.xqar
tests/test_result.py

This PR removes a field that was considered unnecessary for file type, since the framework is meant to be file/standard agnostic.
1. [Remove file type on models](https://github.com/asam-ev/qc-baselib-py/commit/942b7cae8f2a8904f5525ed740a6f942124160f1) 
2. [Remove file type from Result interface](https://github.com/asam-ev/qc-baselib-py/commit/7f02f9ec844a22c421bc87e89ff81e27165c21ca) 
3. [Update tests with field removal](https://github.com/asam-ev/qc-baselib-py/commit/64c52e3751ed27990c85112a9b9ee124e80d756b) 
4. [Remove file type from README example](https://github.com/asam-ev/qc-baselib-py/commit/395289d5c33d7681de3a698c1bf943506855f71b) 
1. Unit-test are working with the updates.
**Notes**
- Related to …

Remove file type from result file location

---

qc_baselib/result.py
tests/data/result_test_output.xqar
tests/test_result.py

This PR adds the option to pass a list of `xpath` locations for creating a XML Location using the `add_xml_location` method on the Result interface.
1. [Add support to list xpath location on add_xml_location](https://github.com/asam-ev/qc-baselib-py/commit/ded906f9c236d236c27bf471b9ca7bddaf45fda2) 
2. [Update tests with new supported option](https://github.com/asam-ev/qc-baselib-py/commit/4a12af3f0c34dea3f275e736eb2c68f91ea39885)First change
1. Unit-test are passing with the updates.
**Notes**

Add support for multiple xpath on Result add_xml_location

---

README.md
qc_baselib/models/result.py
qc_baselib/result.py
tests/data/result_test_output.xqar
tests/test_result.py

This PR removes the file type from the result format and supports for adding multiple XPath on Result.add_xml_location method.
1. #14 
2. #15 
1. Tests are documented in each individual PR.
**Notes**
Close https://github.com/asam-ev/qc-framework/issues/99.

Remove file type from result format and add a minor improvement

---

qc_baselib/models/result.py
report_modules/report_module_text/report_format_text.py
report_modules/report_module_text/run.sh

Add text report module in python
1. Unit-test with  sample data. All unit tests passed.
**Notes**
Example output
```
======================================================================================================
Python Text Report Module - Pooled Results
======================================================================================================
CheckerBundle: DemoCheckerBundle
Build date: 
Build version: 
Description: 
Summary: Found 1 issue
====================
Checkers:
====================
Checker:        exampleChecker
Description:    This is a description
Status:    
Summary:        
====================
Issues:
====================
Issue:              0
Description:        This is an information from the demo usecase …
```

Add text report module in python

---

examples/json_validator/README.md
examples/json_validator/config/invalid.xml
examples/json_validator/config/valid.xml
examples/json_validator/data/invalid.json
examples/json_validator/data/valid.json
examples/json_validator/json_validator.py
examples/json_validator/requirements.txt

Add example to show how to use base library for a custom checker bundle. In particular the example shows a json validation executed with base library configuration and result objects usage
1. Unit-test with  sample data. All unit tests passed.
**Notes**
Example execution
```
python json_validator.py \
-c config/invalid.xml
2024-08-05 10:38:11,946 - Initializing checks
2024-08-05 10:38:11,946 - JsonFile = data/invalid.json
2024-08-05 10:38:11,946 - resultFile = json_bundle_report.xqar
2024-08-05 10:38:11,947 - Issues found - 1
2024-08-05 10:38:11,947 - Report file written to json_bundle_report.xqar
2024-08-05 10:38:11,947 - Done
```

Add json validator example

---

qc_baselib/result.py
tests/data/result_markdown_docs.md
tests/test_result.py

This PR adds a simple function to output the report markdown documentation.
The test output rendered as markdown:
---
- Build date:     2024-05-31
- Build version:  0.0.1
- Description:    Example checker bundle
- Summary:        Tested example checkers
* None
* Description: Test checker
* Status:      
* Summary:     Executed evaluation
+ Addressed rules:
1. test.com:qc:1.0.0:qwerty.qwerty
---
1. Add write_markdown_docs to Result class
2. Add tests to markdown docs function
1. Unit-tests for the desired output
2. Tested with a few results loaded from checker bundles executions.
**Notes**
- Related to https://github.com/asam-ev/qc-framework/issues/27

Add result markdown docs

---

poetry.lock
pyproject.toml

This PR updates the package distribution name to `asam-qc-baselib` while the import package name stays as `qc_baselib`.
1. Update distribution package name to asam-qc-baselib
1. Unit-tests are working as expected.
**Notes**
- It is important to notice that the import name was not updated. We need to verify if it will be necessary.

Update distribution package name to asam-qc-baselib

---

qc_baselib/models/config.py
qc_baselib/models/result.py
tests/data/ordered_config.xml
tests/data/unordered_config.xml
tests/test_configuration.py

This PR adds a fix for an issue where the models where parsing wrongly the XML files because they were expecting a given order for the elements. With this new implementation the order does not matter anymore and all elements will be parsed.
1. Add search mode unordered to elements with more than one sub-element
2. Add tests for the order independence of the models
1. Unit-test with some sample data for order difference.
**Notes**
- None.

Fix models search mode to catch all sub-elements occurrences 

---

qc_baselib/configuration.py
tests/test_configuration.py

This PR adds some helper functions to return all checkers bundles and report modules registered in a configuration.
1. Add get all methods
2. Add tests for new functions
1. Unit-test with new functions test cases.
**Notes**
- None.

Add get all methods for checker bundles and report modules

---

requirements.txt

Keeping requirements.txt makes the dependency information duplicated. It also creates confusing behavior when users install this package via pip, as it's not clear what transitive dependencies will be installed.
Now, dependencies can only be specified in `pyproject.toml`.
Example issue caused by `requirements.txt`: https://github.com/asam-ev/qc-openscenarioxml/actions/runs/10496425116/job/29077033846
1. Removed requirements.txt.
1. Unit-test and testing via qc-openscenarioxml import.
**Notes**

Remove requirements.txt as we use pyproject.toml

---

qc_baselib/result.py

Add a warning when multiple rules are registered to a check.
See also 
1. First change
2. Second change
1. Tested via qc_opendrive and see that the warning is printed out correctly.
**Notes**
Related issue: 
* https://github.com/asam-ev/qc-framework/issues/163

Add a warning message when multiple rules are registered to a check

---

qc_baselib/result.py
tests/test_result.py

Make summary optional when registering checkers and checker bundles as it's not mandatory for users to set it.
There will be another PR to automatically create a summary and append it to the summary created by users.
1. Make summary optional when registering checkers and checker bundles
1. Unit-test
**Notes**
Related issue:
* https://github.com/asam-ev/qc-framework/issues/161

Make summary as optional when register checkers and checker bundles

---

qc_baselib/result.py
tests/test_result.py

Add functions to query checker status.
1. Add a function to get checker status.
2. Add a function to check if all checkers are completed.
1. Unit-test
**Notes**

Add helper functions for query checker status

---

qc_baselib/result.py
tests/data/result_test_output.xqar
tests/test_result.py

Add an option to generate summaries for checker bundles and checkers automatically when `write_to_file` and add methods to add summaries to checker bundle and checker. 
1. Add an option to generate summaries for checker bundles and checkers automatically when `write_to_file`.
2. Add methods to add summaries to checker bundles and checkers. 
1. Unit-test
**Notes**
Related issues:
* https://github.com/asam-ev/qc-framework/issues/161

Add methods to generate summary and add summary

---

qc_baselib/configuration.py
qc_baselib/models/result.py
qc_baselib/result.py
tests/data/result_markdown_docs.md
tests/test_configuration.py
tests/test_result.py

This PR adds some methods to add and get parameters on the Result object.
It also include a change in the Configuration for supporting the new Result copy method.
1. [Add params xml Param attribute to CheckerType model](https://github.com/asam-ev/qc-baselib-py/commit/e8d1d805131867a8ff321582d97789aee7fcdc21) 
2. [Add method to get all global configuration params from Configuration](https://github.com/asam-ev/qc-baselib-py/commit/a019bc597bee9692b047628a750c876ff81a5372) 
3. [Add complete copy configuration to Result](https://github.com/asam-ev/qc-baselib-py/commit/20d62b927f9110bf0080430c491f9ce73338a405) 
4. [Add test to new parameter methods on Result](https://github.com/asam-ev/qc-baselib-py/commit/f98f7e56bb7967d11c33087b6b3927388ab95685) 
5. [Add test …

Add methods to add parameters on Result

---

qc_baselib/result.py
tests/test_result.py

This PR adds the validation for the registration of duplicated:
- Checker bundles;
- Checkers;
- Parameters;
on the Result object.
1. [Add duplicate validation on registration methods](https://github.com/asam-ev/qc-baselib-py/commit/633936a5c8d758ed42d5fc91a6ca2f28f293b7f0)
2. [Add tests for new validation behavior](https://github.com/asam-ev/qc-baselib-py/commit/d1e3e8b44cffa9839e5662ae5c3f9338272bfcd1)
1. Unit-test.
**Notes**
- None.

Add duplicate validation to registration methods

---

qc_baselib/result.py
tests/test_result.py

This PR fixes an issue in the `copy_param_from_config` method. This method will raise an error in case a checker bundle or a checker in the config file is not registered in the result file. It is expected that there will be no error and the params are simply not copied in those cases.
1. Unit-test
**Notes**

Fix an issue in copy_param_from_config

---

examples/json_validator/README.md
examples/json_validator/config/skipped.xml
examples/json_validator/json_validator.py
examples/json_validator/requirements.txt
qc_baselib/configuration.py
qc_baselib/models/result.py
qc_baselib/result.py
tests/data/result_markdown_docs.md
tests/data/result_test_output.xqar
tests/test_configuration.py
tests/test_result.py

This PR adds various minor maintenance tasks.
1. Update the checker bundle example to show how to set status of checker and how to add documentation generator.
* #36 
1. Add a function to automatically generate the summary for each checker and checker bundle. Also add a function to allow users to add more information to the summary.
* #37 
1. Support parameters for each checker and add a function to copy all parameters from a config file to a result file.
* #38 
* #42 
1. Add validation for duplicated registrations (like register the same checker twice).
* #39 
1. Allow users to register rule by rule uid string directly.
* #40 
1. Tests are included in each PR.
**Notes**
This PR closes the following issue:
* …

Add maintenance work

---

README.md
examples/json_validator/requirements.txt
examples/report_module_text/requirements.txt
pyproject.toml
qc_baselib/__init__.py
qc_baselib/configuration.py
qc_baselib/models/config.py
qc_baselib/models/result.py
qc_baselib/result.py
tests/test_result.py

This PR prepares the release candidate 1.0.0rc1.
1. Update all the reference to the main branch.
2. Add disclaimer about the release candidate.
3. Make `build_time` optional when registering checker bundle. If `build_time` is not provided, the current datetime will be used as build time (see https://github.com/asam-ev/qc-opendrive/issues/108)
1. Unit-test
**Notes**
Related issue: https://github.com/asam-ev/qc-opendrive/issues/108

Prepare for the release candidate 1.0.0rc1

---

README.md
examples/json_validator/requirements.txt
examples/report_module_text/requirements.txt
pyproject.toml
qc_baselib/__init__.py
qc_baselib/configuration.py
qc_baselib/models/config.py
qc_baselib/models/result.py
qc_baselib/result.py
tests/test_result.py

As discussed in the QC Framework meeting this week, this PR prepares for the release candidate 1.0.0rc1. After this PR is merged into `main`, the tag `v1.0.0-rc1` and the release candidate `1.0.0rc1` for `asam-qc-baselib` will be created.
Other checker bundles will be updated after `asam-qc-baselib` is released, so they can point to `1.0.0rc1`.
1. Make `build_date` optional when registering a checker bundle. If `build_date` is not provided, use the current execution date as `build_date`.
2. Add disclaimer for `1.0.0rc1`.
3. All the references now point to `main` instead of `develop`.
4. Bump version to `1.0.0rc1`.
1. Unit-test
**Notes**
Related issue: https://github.com/asam-ev/qc-opendrive/issues/108

For CCB Review: Prepare for the release candidate v1.0.0-rc.1

---

README.md
examples/json_validator/config/invalid.xml
examples/json_validator/config/skipped.xml
examples/json_validator/config/valid.xml
examples/json_validator/json_validator.py
examples/json_validator/requirements.txt
examples/report_module_text/requirements.txt

This PR adds the installation from PyPi README and updates the minimum json checker bundle example to use the latest development in `qc_baselib`.
1. Add `pip install asam-qc-baselib` to installation instruction in README.
2. Update json checker bundle to install `asam-qc-baselib` from PyPi and use the latest development from `qc_baselib`.
1. Unit-test
2. Tested json validator checker bundle manually with the 3 provided config files.
3. Render readme locally.
**Notes**

Update documentation and example

---

LICENSE
examples/json_validator/json_validator.py
examples/report_module_text/report_format_text.py
qc_baselib/__init__.py
qc_baselib/configuration.py
qc_baselib/models/__init__.py
qc_baselib/models/common.py
qc_baselib/models/config.py
qc_baselib/models/result.py
qc_baselib/result.py
tests/__init__.py
tests/test_configuration.py
tests/test_models.py
tests/test_result.py

Add copyright and SPDX-License-Identifier to source code files.
1. Add copyright to LICENSE file.
2. Add SPDX-License-Identifier to source code files.
3. Add some missing license headers.
1. Unit-test
**Notes**
Related issue: https://github.com/asam-ev/qc-framework/issues/94

Add copyright and SPDX-License-Identifier

---

qc_baselib/configuration.py
tests/test_configuration.py

Currently if the set functions are called for an existing parameter, a new param entry is just appended, which will then not take any effect, as we always return the first entry on the getters.
This is not obviously the behavior one would expect from a setter (rather than an appender), hence this PR changes the semantics to properly update the first found existing entry, if present.
This is a minimalistic change, and is still robust against multiple param entries for the same name already existing (e.g. in loaded files), while still ensuring that any newly set parameters override the existing parameter value, which is useful for the checker bundles in handling command-line arguments for overriding of information in the configuration.

Make setting of params override any existing one
